### ISSUE TITLE
EF Migrations is not working

### ISSUE THREAD

**Issue by jdphenix** [DevChatter/devchatterbot#102]
Any migration attempt will fail with `System.ArgumentNullException`. This occurs because the `AppDataContextFactory` is not aware of the new configuration structure.

> PM> Add-Migration AbstractedCommandWords
System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at Microsoft.EntityFrameworkCore.Utilities.Check.NotEmpty(String value, String parameterName)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(DbContextOptionsBuilder optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
   at Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer[TContext](DbContextOptionsBuilder`1 optionsBuilder, String connectionString, Action`1 sqlServerOptionsAction)
   at DevChatter.Bot.Infra.Ef.AppDataContextFactory.CreateDbContext(String[] args) in C:\Users\jdphe\source\sourcetree\devchatterbot-jdphenix\src\DevChatter.Bot.Infra.Ef\AppDataContext.cs:line 35
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContextFromFactory(Type factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass14_0.<FindContextFactory>b__1()
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null.
Parameter name: connectionString

**Comment by skyhoshi** [comment]
What happens when you specify a specific project in either the command or the Package Manager window itself? 

When I've seen this before the project referenced in the Package Manager / Powershell console is not pointed to the same project where the model lives and thus when EF attempts to retrieve a backing database connection string this error happens. 
More specifically the EF is attempting to ascertain the Provider type (Context's Backing Provider type). (System.Data.SqlClient) when EF's Model specifies a connection string name, and it cannot find that CS in the config files. 
There's a couple solutions to this problem. (if it is the same problem) 

1. Ensure the IDE Package Manager window is pointed to the correct project with the proper configuration connection string. (correct me if i'm wrong but if your dealing with EF 6 in the project that is NOT core (dotnetCore/standard)  and there are core projects in the solution; the Core projects can create some difficulty in this process (not returning a Connection string) [This may not be true anymore]
2. Provide the Project name in the command being executed. 
3. Provide the Provider Type in the command being executed AND / OR Remove the hard coded Connection string name in the model but this would then require you to provide the Provider type when doing any of the commands from the console.

let us know how this goes. I'd be happy to provide any additional assistance and Trouble shoot a branch if you would like or need.

**Comment by benrick** [comment]
Good catch. That's very correct.

**Comment by benrick** [comment]
Merged the commit that should resolve this.
